# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg1MSP

        # ID to load the MSP definition as
        ID: OrdererOrg1MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: ../crypto-config/ordererOrganizations/org1.example.com/msp

        Policies: &OrdererOrg1Policy
            Readers:
                Type: Signature
                Rule: "OR('OrdererOrg1MSP.member')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('SampleOrg.admin', 'SampleOrg.peer', 'SampleOrg.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererOrg1MSP.member')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('SampleOrg.admin', 'SampleOrg.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererOrg1MSP.admin')"


    - &OrdererOrg2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg2MSP

        # ID to load the MSP definition as
        ID: OrdererOrg2MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: ../crypto-config/ordererOrganizations/org2.example.com/msp

        Policies: &OrdererOrg2Policy
            Readers:
                Type: Signature
                Rule: "OR('OrdererOrg2MSP.member')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('SampleOrg.admin', 'SampleOrg.peer', 'SampleOrg.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererOrg2MSP.member')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('SampleOrg.admin', 'SampleOrg.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererOrg2MSP.admin')"


    - &Org1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org1MSP

        # ID to load the MSP definition as
        ID: Org1MSP

        MSPDir: ../crypto-config/peerOrganizations/org1.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('SampleOrg.admin', 'SampleOrg.peer', 'SampleOrg.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('SampleOrg.admin', 'SampleOrg.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"

        # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org1.example.com
              Port: 7051

    - &Org2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org2MSP

        # ID to load the MSP definition as
        ID: Org2MSP

        MSPDir: ../crypto-config/peerOrganizations/org2.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('SampleOrg.admin', 'SampleOrg.peer', 'SampleOrg.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
                # If your MSP is configured with the new NodeOUs, you might
                # want to use a more specific rule like the following:
                # Rule: "OR('SampleOrg.admin', 'SampleOrg.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org2.example.com
              Port: 7051


################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
    # Policies defines the set of policies at this level of the config tree
    # For Channel policies, their canonical path is
    #   /Channel/<PolicyName>
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    # Capabilities describes the channel level capabilities, see the
    # dedicated Capabilities section elsewhere in this file for a full
    # description
    #Capabilities:
        #<<: *ChannelCapabilities

Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    TwoOrgsChannel:
        <<: *ChannelDefaults
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
            #Capabilities:
                #<<: *ApplicationCapabilities


    SampleMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        #Capabilities:
            #<<: *ChannelCapabilities
        Orderer:
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer0.org1.example.com
                  Port: 7050
                  ClientTLSCert: ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer0.org1.example.com/tls/server.crt
                  ServerTLSCert: ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer0.org1.example.com/tls/server.crt
                - Host: orderer1.org1.example.com
                  Port: 7050
                  ClientTLSCert: ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer1.org1.example.com/tls/server.crt
                  ServerTLSCert: ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer1.org1.example.com/tls/server.crt
                - Host: orderer0.org2.example.com
                  Port: 7050
                  ClientTLSCert: ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer0.org2.example.com/tls/server.crt
                  ServerTLSCert: ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer0.org2.example.com/tls/server.crt
                - Host: orderer1.org2.example.com
                  Port: 7050
                  ClientTLSCert: ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer1.org2.example.com/tls/server.crt
                  ServerTLSCert: ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer1.org2.example.com/tls/server.crt

                Options:
                  TickInterval: 500ms
                  ElectionTick: 10
                  HeartbeatTick: 1
                  MaxInflightBlocks: 5
                  SnapshotIntervalSize: 20 MB

            Addresses:
              - orderer0.org1.example.com:7050
              - orderer1.org1.example.com:7050
              - orderer0.org2.example.com:7050
              - orderer1.org2.example.com:7050

            Organizations:
              - *OrdererOrg1
              - *OrdererOrg2

            #Capabilities:
                #<<: *OrdererCapabilities

            Policies:
                Readers:
                  Type: ImplicitMeta
                  Rule: "ANY Readers"
                Writers:
                  Type: ImplicitMeta
                  Rule: "ANY Writers"
                Admins:
                  Type: ImplicitMeta
                  Rule: "MAJORITY Admins"

        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg1
            - <<: *OrdererOrg2

        Consortiums:
            SampleConsortium:
                Organizations:
                  - *Org1
                  - *Org2
