# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            Organizations:
                - *Org1
                - *Org2


    SampleMultiNodeEtcdRaft:
        Orderer:
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer0.org1.example.com
                  Port: 7050
                  ClientTLSCert: ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer0.org1.example.com/tls/server.crt
                  ServerTLSCert: ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer0.org1.example.com/tls/server.crt
                - Host: orderer1.org1.example.com
                  Port: 8050
                  ClientTLSCert: ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer1.org1.example.com/tls/server.crt
                  ServerTLSCert: ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer1.org1.example.com/tls/server.crt
                - Host: orderer0.org2.example.com
                  Port: 7050
                  ClientTLSCert: ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer0.org2.example.com/tls/server.crt
                  ServerTLSCert: ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer0.org2.example.com/tls/server.crt
                - Host: orderer1.org2.example.com
                  Port: 8050
                  ClientTLSCert: ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer1.org2.example.com/tls/server.crt
                  ServerTLSCert: ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer1.org2.example.com/tls/server.crt

            Addresses:
                - orderer0.org1.example.com:7050
                - orderer1.org1.example.com:8050
                - orderer0.org2.example.com:7050
                - orderer1.org2.example.com:8050


            Organizations:
            - *OrdererOrg1
            - *OrdererOrg2

        Consortiums:
            SampleConsortium:
                Organizations:
                - *Org1
                - *Org2
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg1

        # ID to load the MSP definition as
        ID: Orderer1MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: ../crypto-config/ordererOrganizations/org1.example.com/msp

                
    - &OrdererOrg2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg2

        # ID to load the MSP definition as
        ID: Orderer2MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: ../crypto-config/ordererOrganizations/org2.example.com/msp

    - &Org1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org1MSP

        # ID to load the MSP definition as
        ID: Org1MSP

        MSPDir: ../crypto-config/peerOrganizations/org1.example.com/msp


        # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org1.example.com
              Port: 7051

    - &Org2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org2MSP

        # ID to load the MSP definition as
        ID: Org2MSP

        MSPDir: ../crypto-config/peerOrganizations/org2.example.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org2.example.com
              Port: 7051

