# Configuration for Orderer Nodes of Org2

version: '2'

networks:
    behave:


services:
    ca0.org2.example.com:
        image: hyperledger/fabric-ca
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca0.org2.example.com
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9f540427473f1d41dd679c4b7020e7c37e226fa86256f55e60fc06ac90b99131_sk
            - FABRIC_CA_SERVER_PORT=7054
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.org1.example.com:${IP_SERVER_1}"
            - "orderer1.org1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ../crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca0.org2.example.com
        networks:
           behave:
             aliases:
                - ${CORE_PEER_NETWORKID}

    ca1.org2.example.com:
        image: hyperledger/fabric-ca
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca1.org2.example.com
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d641b4a0caed87cebe78f424f4b6bbb6a20c6270f1b6864ea9ad3979615ef873_sk
            - FABRIC_CA_SERVER_PORT=8054
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.org1.example.com:${IP_SERVER_1}"
            - "orderer1.org1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        ports:
            - "8054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ../crypto-config/ordererOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca1.org2.example.com
        networks:
           behave:
             aliases:
                - ${CORE_PEER_NETWORKID}


    orderer0.org2.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer0.org2.example.com
        environment:
            - ORDERER_HOST=orderer0.org2.example.com
            - CONFIGTX_ORDERER_ORDERERTYPE=etcdraft
            - ORDERER_GENERAL_GENESISPROFILE=SampleMultiNodeEtcdRaft
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
            - ORDERER_GENERAL_LOCALMSPID=Orderer2MSP
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.org1.example.com:${IP_SERVER_1}"
            - "orderer1.org1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        volumes:
            - ../crypto-config/ordererOrganizations/org2.example.com/users/Admin@org2.example.com:/var/hyperledger/users/Admin@example.com
            - ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer0.org2.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer0.org2.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 7050:7050

    orderer1.org2.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer1.org2.example.com
        environment:
            - ORDERER_HOST=orderer1.org2.example.com
            - CONFIGTX_ORDERER_ORDERERTYPE=etcdraft
            - ORDERER_GENERAL_GENESISPROFILE=SampleMultiNodeEtcdRaft
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
            - ORDERER_GENERAL_LOCALMSPID=Orderer2MSP
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.org1.example.com:${IP_SERVER_1}"
            - "orderer1.org1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        volumes:
            - ../crypto-config/ordererOrganizations/org2.example.com/users/Admin@org2.example.com:/var/hyperledger/users/Admin@example.com
            - ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer1.org2.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer1.org2.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 8050:7050
