# Configuration for Orderer Nodes of Org1

version: '2'

volumes:
  orderer0.org1.example.com:
  orderer1.org1.example.com:

networks:
    behave:

services:
    ca.org1.example.com:
        image: hyperledger/fabric-ca:${HLF_VERSION_TAG}
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5d178c70a3518dc54938f272934ae44c26c24d73aeb00b699efb5a3d14b4760a_sk
            - FABRIC_CA_SERVER_PORT=7054
        extra_hosts:
            - "peer0.org2.example.com:${IP_SERVER_2}"
            - "peer1.org2.example.com:${IP_SERVER_2}"
            - "orderer0.org2.example.com:${IP_SERVER_2}"
            - "orderer1.org2.example.com:${IP_SERVER_2}"
            - "ca.org2.example.com:${IP_SERVER_2}"
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca.org1.example.com
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    orderer0.org1.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer0.org1.example.com
        environment:
            - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
        extra_hosts:
            - "peer0.org2.example.com:${IP_SERVER_2}"
            - "peer1.org2.example.com:${IP_SERVER_2}"
            - "orderer0.org2.example.com:${IP_SERVER_2}"
            - "orderer1.org2.example.com:${IP_SERVER_2}"
            - "ca.org2.example.com:${IP_SERVER_2}"
        volumes:
            - ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer0.org1.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer0.org1.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer0.org1.example.com:/var/hyperledger/production/orderer
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 7050:7050

    orderer1.org1.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer1.org1.example.com
        environment:
            - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
        extra_hosts:
            - "peer0.org2.example.com:${IP_SERVER_2}"
            - "peer1.org2.example.com:${IP_SERVER_2}"
            - "orderer0.org2.example.com:${IP_SERVER_2}"
            - "orderer1.org2.example.com:${IP_SERVER_2}"
            - "ca.org2.example.com:${IP_SERVER_2}"
        volumes:
            - ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer1.org1.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer1.org1.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer1.org1.example.com:/var/hyperledger/production/orderer
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 8050:7050
