# Configuration for Orderer Nodes of Org2

version: '3'

networks:
    net:
      external:
        name: net

volumes:
  orderer0.ordererOrg2.example.com:
  orderer1.ordererOrg2.example.com:

services:
    orderer0.ordererOrg2.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer0.ordererOrg2.example.com
        environment:
            - ORDERER_HOST=orderer0.ordererOrg2.example.com
            - ORDERER_GENERAL_LOCALMSPID=OrdererOrg2MSP
        volumes:
            - ../crypto-config/ordererOrganizations/ordererOrg2.example.com/orderers/orderer0.ordererOrg2.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/ordererOrg2.example.com/orderers/orderer0.ordererOrg2.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer0.ordererOrg2.example.com:/var/hyperledger/production/orderer
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == ${IP_SERVER_2}
        networks:
          net:
             aliases:
               - orderer0.ordererOrg2.example.com
        ports:
          - 7050:7050

    orderer1.ordererOrg2.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer1.ordererOrg2.example.com
        environment:
            - ORDERER_HOST=orderer1.ordererOrg2.example.com
            - ORDERER_GENERAL_LOCALMSPID=OrdererOrg2MSP
            - ORDERER_GENERAL_LISTENPORT=8050
        volumes:
            - ../crypto-config/ordererOrganizations/ordererOrg2.example.com/orderers/orderer1.ordererOrg2.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/ordererOrg2.example.com/orderers/orderer1.ordererOrg2.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer1.ordererOrg2.example.com:/var/hyperledger/production/orderer
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == ${IP_SERVER_2}
        networks:
          net:
             aliases:
               - orderer1.ordererOrg2.example.com
        ports:
          - 8050:7050
