# Configuration for Orderer Nodes of Org1

version: '3.4'
volumes:
  orderer0.ordererOrg1.example.com:
  orderer1.ordererOrg1.example.com:

networks:
    net:
      external:
        name: net

services:
    orderer0_ordererOrg1_example_com:
        image: hyperledger/fabric-orderer:1.4.1
        hostname: orderer0.ordererOrg1.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - DISCOVERY_AS_LOCALHOST=false
            - ORDERER_HOME=/var/hyperledger/orderer
            - FABRIC_LOGGING_SPEC=debug
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/configs/orderer.block
              # TLS settings
            - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_HOST=orderer0.ordererOrg1.example.com
            - ORDERER_GENERAL_LOCALMSPID=OrdererOrg1MSP
        volumes:
            - ../crypto-config/ordererOrganizations/ordererOrg1.example.com/orderers/orderer0.ordererOrg1.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/ordererOrg1.example.com/orderers/orderer0.ordererOrg1.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer0.ordererOrg1.example.com:/var/hyperledger/production/orderer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == maurice-mobile
        networks:
          net:
             aliases:
               - orderer0.ordererOrg1.example.com
        ports:
          - 7050:7050

    orderer1_ordererOrg1_example_com:
        image: hyperledger/fabric-orderer:1.4.1
        hostname: orderer1.ordererOrg1.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - DISCOVERY_AS_LOCALHOST=false
            - ORDERER_HOME=/var/hyperledger/orderer
            - FABRIC_LOGGING_SPEC=debug
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/configs/orderer.block
            # TLS settings
            - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_HOST=orderer1.ordererOrg1.example.com
            - ORDERER_GENERAL_LOCALMSPID=OrdererOrg1MSP
        volumes:
            - ../crypto-config/ordererOrganizations/ordererOrg1.example.com/orderers/orderer1.ordererOrg1.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/ordererOrg1.example.com/orderers/orderer1.ordererOrg1.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer1.ordererOrg1.example.com:/var/hyperledger/production/orderer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == maurice-mobile
        networks:
          net:
             aliases:
               - orderer1.ordererOrg1.example.com
        ports:
          - 8050:7050
