# Configuration for Orderer Nodes of Org2

version: '2'

networks:
    behave:


services:
    ca.org2.example.com:
        image: hyperledger/fabric-ca
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/93fe055da3b67bd64c8785070605bb77c69866cfc5d3c37ed750ed259e6e60b3_sk
            - FABRIC_CA_SERVER_PORT=7054
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.org1.example.com:${IP_SERVER_1}"
            - "orderer1.org1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ../crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca.org2.example.com
        networks:
           behave:
             aliases:
                - ${CORE_PEER_NETWORKID}

    orderer0.org2.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer0.org2.example.com
        environment:
            - ORDERER_HOST=orderer0.org2.example.com
            - CONFIGTX_ORDERER_ORDERERTYPE=etcdraft
            - ORDERER_GENERAL_GENESISPROFILE=SampleMultiNodeEtcdRaft
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
            - ORDERER_GENERAL_LOCALMSPID=Orderer2MSP
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.org1.example.com:${IP_SERVER_1}"
            - "orderer1.org1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        volumes:
            - ../crypto-config/ordererOrganizations/org2.example.com/users:/var/hyperledger/users
            - ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer0.org2.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer0.org2.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 7050:7050

    orderer1.org2.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer1.org2.example.com
        environment:
            - ORDERER_HOST=orderer1.org2.example.com
            - CONFIGTX_ORDERER_ORDERERTYPE=etcdraft
            - ORDERER_GENERAL_GENESISPROFILE=SampleMultiNodeEtcdRaft
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
            - ORDERER_GENERAL_LOCALMSPID=Orderer2MSP
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.org1.example.com:${IP_SERVER_1}"
            - "orderer1.org1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        volumes:
            - ../crypto-config/ordererOrganizations/org2.example.com/users:/var/hyperledger/users
            - ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer1.org2.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/org2.example.com/orderers/orderer1.org2.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 8050:7050
