version: '2'

networks:
  behave:

services:
  ca.org2.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/93fe055da3b67bd64c8785070605bb77c69866cfc5d3c37ed750ed259e6e60b3_sk
      - FABRIC_CA_SERVER_PORT=7054
    extra_hosts:
      - "peer0.org1.example.com:${IP_SERVER_1}"
      - "peer1.org1.example.com:${IP_SERVER_1}"
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/93fe055da3b67bd64c8785070605bb77c69866cfc5d3c37ed750ed259e6e60b3_sk  -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org2.example.com
    networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}