# Configuration for Orderer Nodes of Org2

version: '2'

networks:
    behave:

volumes:
  orderer2.example.com:
  orderer3.example.com:

services:
    ca.org2.example.com:
        image: hyperledger/fabric-ca:${HLF_VERSION_TAG}
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a24cc3eefcf49dd68156c018bf2d046e481b79d8b44fa9c3887b5ab209b063d3_sk
            - FABRIC_CA_SERVER_PORT=7054
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.example.com:${IP_SERVER_1}"
            - "orderer1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ../crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca.org2.example.com
        networks:
           behave:
             aliases:
                - ${CORE_PEER_NETWORKID}


    orderer2.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer2.example.com
        environment:
            - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.example.com:${IP_SERVER_1}"
            - "orderer1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        volumes:
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer2.example.com:/var/hyperledger/production/orderer
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 9050:7050

    orderer3.example.com:
        extends:
            file: docker-compose-base.yaml
            service: orderer
        container_name: orderer3.example.com
        environment:
            - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
        extra_hosts:
            - "peer0.org1.example.com:${IP_SERVER_1}"
            - "peer1.org1.example.com:${IP_SERVER_1}"
            - "orderer0.example.com:${IP_SERVER_1}"
            - "orderer1.example.com:${IP_SERVER_1}"
            - "ca.org1.example.com:${IP_SERVER_1}"
        volumes:
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer3.example.com:/var/hyperledger/production/orderer
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 10050:7050
