# Configuration for Peer 0 & Peer1 of Org1

version: '3.4'

volumes:
    peer0.org1.example.com:
    peer1.org1.example.com:

networks:
    net:
      external:
        name: net

services:
    peer0_org1_example_com:
        hostname: peer0.org1.example.com
        image: hyperledger/fabric-peer:1.4.1
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - DISCOVERY_AS_LOCALHOST=false
            - CORE_PEER_NETWORKID=net
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peers/msp
            - CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_LOGGING_MSP=DEBUG
            # TLS settings
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/peers/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/peers/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/peers/tls/ca.crt
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_ID=peer0.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org1.example.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org1.example.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org1.example.com/tls/client.key
        volumes:
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/peers/msp
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/peers/tls
            - ../crypto-config/peerOrganizations/org1.example.com/users:/var/hyperledger/users
            - /var/run/:/host/var/run/
            - /home/maurice/goproject/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            - peer0.org1.example.com:/var/hyperledger/production
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == maurice-mobile
        networks:
          net:
             aliases:
               - peer0.org1.example.com
        ports:
          - 7051:7051
          - 7053:7053

    peer1_org1_example_com:
        hostname: peer1.org1.example.com
        image: hyperledger/fabric-peer:1.4.1
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - DISCOVERY_AS_LOCALHOST=false
            - CORE_PEER_NETWORKID=net
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peers/msp
            - CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_LOGGING_MSP=DEBUG
            # TLS settings
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/peers/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/peers/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/peers/tls/ca.crt
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org1.example.com:8052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
            - CORE_PEER_ID=peer1.org1.example.com
            - CORE_PEER_ADDRESS=peer1.org1.example.com:8051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:8051
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org1.example.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org1.example.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org1.example.com/tls/client.key
        volumes:
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/var/hyperledger/peers/msp
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/var/hyperledger/peers/tls
            - ../crypto-config/peerOrganizations/org1.example.com/users:/var/hyperledger/users
            - /var/run/:/host/var/run/
            - /home/maurice/goproject/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            - peer1.org1.example.com:/var/hyperledger/production
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == maurice-mobile
        networks:
          net:
             aliases:
               - peer1.org1.example.com
        ports:
          - 8051:8051
          - 8053:8053
