# Configuration for Orderer Nodes of Org1

version: '2'

services:
    orderer0.org1.example.com:
        extends:
            file: docker-compose-base.yml
            service: orderer
        container_name: orderer0.org1.example.com
        environment:
            - ORDERER_HOST=orderer0.org1.example.com
            - CONFIGTX_ORDERER_ORDERERTYPE=etcdraft
            - ORDERER_GENERAL_GENESISPROFILE=SampleMultiNodeEtcdRaft
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
            - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
        extra_hosts:
            - "peer0.org2.example.com:${IP_SERVER_2}"
            - "peer1.org2.example.com:${IP_SERVER_2}"
            - "orderer0.org2.example.com:${IP_SERVER_2}"
            - "orderer0.org2.example.com:${IP_SERVER_2}"
            - "ca.org2.example.com:${IP_SERVER_2}"
        volumes:
            - ../crypto-config/ordererOrganizations/org1.example.com/users:/var/hyperledger/users
            - ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer0.org1.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer0.org1.example.com/tls:/var/hyperledger/tls
            - ../network-config/:/var/hyperledger/configs
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 7050:7050
          
    orderer1.org1.example.com:
        extends:
            file: docker-compose-base.yml
            service: orderer
        container_name: orderer1.org1.example.com
        environment:
            - ORDERER_HOST=orderer1.org1.example.com
            - CONFIGTX_ORDERER_ORDERERTYPE=etcdraft
            - ORDERER_GENERAL_GENESISPROFILE=SampleMultiNodeEtcdRaft
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
            - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
        extra_hosts:
            - "peer0.org2.example.com:${IP_SERVER_2}"
            - "peer1.org2.example.com:${IP_SERVER_2}"
            - "orderer0.org2.example.com:${IP_SERVER_2}"
            - "orderer0.org2.example.com:${IP_SERVER_2}"
            - "ca.org2.example.com:${IP_SERVER_2}"
        volumes:
            - ../crypto-config/ordererOrganizations/org1.example.com/users:/var/hyperledger/users
            - ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer1.org1.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/org1.example.com/orderers/orderer1.org1.example.com/tls:/var/hyperledger/tls
            - ../network-config/:/var/hyperledger/configs
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 8050:7050

