# Configuration for Orderer Nodes of Org2

version: '3.4'

networks:
    net:
      external:
        name: net

volumes:
  orderer0.ordererOrg2.example.com:
  orderer1.ordererOrg2.example.com:

services:
    orderer0_ordererOrg2_example_com:
        hostname: orderer0.ordererOrg2.example.com
        image: hyperledger/fabric-orderer:1.4.1
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
            - DISCOVERY_AS_LOCALHOST=false
            - ORDERER_HOME=/var/hyperledger/orderer
            - FABRIC_LOGGING_SPEC=debug
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/configs/orderer.block
            # TLS settings
            - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
        environment:
            - ORDERER_HOST=orderer0.ordererOrg2.example.com
            - ORDERER_GENERAL_LOCALMSPID=OrdererOrg2MSP
        volumes:
            - ../crypto-config/ordererOrganizations/ordererOrg2.example.com/orderers/orderer0.ordererOrg2.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/ordererOrg2.example.com/orderers/orderer0.ordererOrg2.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer0.ordererOrg2.example.com:/var/hyperledger/production/orderer
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == maurice-TERRA-PC
        networks:
          net:
             aliases:
               - orderer0.ordererOrg2.example.com
        ports:
          - 9050:7050

    orderer1_ordererOrg2_example_com:
        hostname: orderer1.ordererOrg2.example.com
        image: hyperledger/fabric-orderer:1.4.1
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
            - DISCOVERY_AS_LOCALHOST=false
            - ORDERER_HOME=/var/hyperledger/orderer
            - FABRIC_LOGGING_SPEC=debug
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/configs/orderer.block
            # TLS settings
            - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_HOST=orderer1.ordererOrg2.example.com
            - ORDERER_GENERAL_LOCALMSPID=OrdererOrg2MSP
            - ORDERER_GENERAL_LISTENPORT=8050
        volumes:
            - ../crypto-config/ordererOrganizations/ordererOrg2.example.com/orderers/orderer1.ordererOrg2.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/ordererOrg2.example.com/orderers/orderer1.ordererOrg2.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer1.ordererOrg2.example.com:/var/hyperledger/production/orderer
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == maurice-TERRA-PC
        networks:
          net:
             aliases:
               - orderer1.ordererOrg2.example.com
        ports:
          - 10050:7050
