# Configuration for Orderer Nodes of Org1

version: '3.4'
volumes:
  orderer0.ordererOrg1.example.com:
  orderer1.ordererOrg1.example.com:

networks:
    net:
      external:
        name: net

services:
    ca_org1_example_com:
        image: hyperledger/fabric-ca:1.4.1
	hostname: ca.org1.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
            - DISCOVERY_AS_LOCALHOST=false
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2bbff32c34bd4fa644525980f82fe11e3336096f81497b4085e92a7431587d02_sk
            - FABRIC_CA_SERVER_PORT=7054
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2bbff32c34bd4fa644525980f82fe11e3336096f81497b4085e92a7431587d02_sk -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == hlf-server1
        networks:
          net:
             aliases:
               - ca.org1.example.com

    orderer0_ordererOrg1_example_com:
        image: hyperledger/fabric-orderer:1.4.1
        hostname: orderer0.ordererOrg1.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
            - DISCOVERY_AS_LOCALHOST=false
            - ORDERER_HOME=/var/hyperledger/orderer
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LOGLEVEL=INFO
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/configs/orderer.block
            # TLS settings
            - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_HOST=orderer0.ordererOrg1.example.com
            - ORDERER_GENERAL_LOCALMSPID=OrdererOrg1MSP
        volumes:
            - ../crypto-config/ordererOrganizations/ordererOrg1.example.com/orderers/orderer0.ordererOrg1.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/ordererOrg1.example.com/orderers/orderer0.ordererOrg1.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer0.ordererOrg1.example.com:/var/hyperledger/production/orderer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == hlf-server1
        networks:
          net:
             aliases:
               - orderer0.ordererOrg1.example.com
        ports:
          - 7050:7050

    orderer1_ordererOrg1_example_com:
        image: hyperledger/fabric-orderer:1.4.1
        hostname: orderer1.ordererOrg1.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
            - DISCOVERY_AS_LOCALHOST=false
            - ORDERER_HOME=/var/hyperledger/orderer
            - ORDERER_GENERAL_LOGLEVEL=INFO
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/configs/orderer.block
            # TLS settings
            - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_HOST=orderer1.ordererOrg1.example.com
            - ORDERER_GENERAL_LOCALMSPID=OrdererOrg1MSP
        volumes:
            - ../crypto-config/ordererOrganizations/ordererOrg1.example.com/orderers/orderer1.ordererOrg1.example.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/ordererOrg1.example.com/orderers/orderer1.ordererOrg1.example.com/tls:/var/hyperledger/orderer/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer1.ordererOrg1.example.com:/var/hyperledger/production/orderer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == hlf-server1
        networks:
          net:
             aliases:
               - orderer1.ordererOrg1.example.com
        ports:
          - 8050:7050
