version: '2'

networks:
  behave:

services:
  ca.org1.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8023f84ca58d473c1ac4a34f6704dccce12b2c8eac62fb76b89530b00a621154_sk
      - FABRIC_CA_SERVER_PORT=7054
    extra_hosts:
      - "peer0.org2.example.com:${IP_SERVER_2}"
      - "peer1.org2.example.com:${IP_SERVER_2}"
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.example.com
    networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}