# Configuration for Peer 0 & Peer1 of Org2

version: '3'

volumes:
    peer0.org2.example.com:
    peer1.org2.example.com:

networks:
    net:
      external:
        name: net

services:
    peer0.org2.example.com:
        extends:
            file: docker-compose-base.yaml
            service: peer
        container_name: peer0.org2.example.com
        environment:
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.example.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_ID=peer0.org2.example.com
            - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER0_ORG2}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER0_ORG2}
            - CORE_PEER_LOCALMSPID=Org2MSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org2.example.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org2.example.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org2.example.com/tls/client.key
        volumes:
            - ../crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/var/hyperledger/peers/msp
            - ../crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/var/hyperledger/peers/tls
            - ../crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
            - ../network-config/:/var/hyperledger/configs
            - peer0.org2.example.com:/var/hyperledger/production
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == ${IP_SERVER_2}
        networks:
          net:
             aliases:
               - peer0.org2.example.com
        ports:
          - 7051:7051
          - 7053:7053

    peer1.org2.example.com:
        extends:
            file: docker-compose-base.yaml
            service: peer
        container_name: peer1.org2.example.com
        environment:
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org2.example.com:8052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_ID=peer1.org2.example.com
            - CORE_PEER_ADDRESS=peer1.org2.example.com:8051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:8051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER0_ORG2}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER0_ORG2}
            - CORE_PEER_LOCALMSPID=Org2MSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org2.example.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org2.example.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org2.example.com/tls/client.key
        volumes:
            - ../crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/var/hyperledger/peers/msp
            - ../crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/var/hyperledger/peers/tls
            - ../crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
            - ../network-config/:/var/hyperledger/configs
            - peer1.org2.example.com:/var/hyperledger/production
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
              condition: on-failure
          placement:
                constraints:
                  - node.hostname == ${IP_SERVER_2}
        networks:
          net:
             aliases:
               - peer1.org2.example.com
        ports:
          - 8051:8051
          - 8053:8053
